#!/usr/bin/env bash
set -euo pipefail

WORKSPACE_DIR="${1:-/mnt/e/GPTProject2/vLLM}"

export VLLM_MODEL="${VLLM_MODEL:-${WORKSPACE_DIR}/models/Qwen3-8B-AWQ}"
export VLLM_TOKENIZER="${VLLM_TOKENIZER:-${VLLM_MODEL}}"
export VLLM_HF_CONFIG_PATH="${VLLM_HF_CONFIG_PATH:-${VLLM_MODEL}}"
export VLLM_SERVED_MODEL_NAME="${VLLM_SERVED_MODEL_NAME:-Qwen3-8B-AWQ-vLLM-local}"
export VLLM_QUANTIZATION="${VLLM_QUANTIZATION:-awq_marlin}"
export VLLM_DTYPE="${VLLM_DTYPE:-auto}"
export VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-2048}"
export VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION:-0.85}"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-2}"
export VLLM_MAX_NUM_BATCHED_TOKENS="${VLLM_MAX_NUM_BATCHED_TOKENS:-4096}"
export VLLM_BLOCK_SIZE="${VLLM_BLOCK_SIZE:-16}"
export VLLM_ENFORCE_EAGER="${VLLM_ENFORCE_EAGER:-1}"

exec bash "${WORKSPACE_DIR}/scripts/start_vllm_gguf_optimized_wsl.sh" "${WORKSPACE_DIR}"
